---
title: "Covid 19 plot using latest data by county and state"
author: "Xiang Lu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include  = FALSE)
library(tidyverse)
library(lubridate)
library(patchwork)
```

```{r input}

myState = "Maryland"
myCounty = "Montgomery"

# state in one of  c("American Samoa", "Guam", "Northern Mariana Islands", "Puerto Rico", 
# "Virgin Islands", "Alabama", "Alaska", "Arizona", "Arkansas", 
# "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", 
# "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", 
# "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
# "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", 
# "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
# "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
# "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", 
# "Grand Princess")

```



```{r filenames, message = FALSE}
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"
file_names <- c("time_series_covid19_confirmed_US.csv",
                "time_series_covid19_deaths_US.csv")
urls <- str_c(url_in,file_names)
```

```{r tidy_US}
US_confirmed <- read_csv(urls[1]) %>%
    pivot_longer(cols = -(UID:Combined_Key), names_to = "Date", values_to = "Confirmed_cases") %>%
    select(Admin2:Confirmed_cases) %>%
    mutate(Date = mdy(Date))
US_deaths <- read_csv(urls[2]) %>%
    pivot_longer(cols = -(UID:Population), names_to = "Date", values_to ="Deaths") %>%
    select(Admin2:Deaths) %>%
    mutate(Date = mdy(Date))



```

```{r join_US_deaths_cases}
US <-  US_deaths %>%
  full_join(US_confirmed, 
            by = c("Combined_Key", "Date", 
                   "Admin2", "Province_State", 
                   "Country_Region")) %>%
    mutate(state = factor(Province_State), 
         county = factor(Admin2)) %>%
    select(county, state, Date, Confirmed_cases, Deaths)

 
mydata <-US %>%
  filter(state == myState, county == myCounty)  

``` 

```{r }
pcase <- mydata %>%
  filter(Confirmed_cases > 0) %>%
  ggplot(aes(x = Date, y = Confirmed_cases )) +
  geom_line() +
  geom_point() + 
  labs(title =  "Confirmed Cases" , x = NULL, y = NULL)  
  

mydataTotals <- mydata %>% 
  group_by(Date) %>%
  summarize(total_cases = sum(Confirmed_cases), 
            total_deaths = sum(Deaths))
  
pdeath <- mydata %>%
  filter(Deaths > 0) %>%
  ggplot(aes(x = Date, y = Deaths)) +
  geom_line(color = "red") +
  geom_point(color = "red") +
  labs(title = "Deaths" , x = NULL, y = NULL)

 
mydata <- mydata %>%
   mutate(new_cases = Confirmed_cases - lag(Confirmed_cases)) 

pnew = mydata %>%
  filter(new_cases > 0) %>%
  ggplot(aes(x = Date, y = new_cases)) +
  geom_line(color = "blue") +
  geom_point(color = "blue") +
  labs(title =  "New Cases" , x = NULL, y = NULL)

```


```{r, include  = TRUE, echo=FALSE}
pcase / pdeath / pnew + plot_annotation(
  title = paste("COVID19 data in", myCounty, ",", myState) 
   
)
```

